#!/usr/bin/env bash
# Compare the current advisory-lint counts against the checked-in baseline
# (.golangci-baseline.txt, regenerated by scripts/lint-baseline.sh).
#
# Policy (round-11 T17): the ~400-finding advisory sea is documented and
# accepted; what the gate refuses is UNBOUNDED GROWTH —
#   - a linter that had zero findings in a module (or no baseline row at
#     all) reporting anything today, or
#   - any module+linter count exceeding its baseline row by more than
#     baselineGrowthAllowance percent.
# Neither fires on the steady hum of small drift; both fire on the failure
# mode that actually hurts (a new class of noise arriving en masse).
#
# Input: the aggregated lint output of the full root+sub-module loop with
# "== module" markers (as emitted by scripts/ci-local.sh's lint step), read
# from $1 or stdin. Rows look like golangci-lint's footer: "* linter: N".
set -euo pipefail
cd "$(dirname "$0")/.."

baseline_file=".golangci-baseline.txt"
input="${1:-/dev/stdin}"

if [ ! -f "$baseline_file" ]; then
	echo "check-lint-baseline: $baseline_file missing — run scripts/lint-baseline.sh"
	exit 1
fi

baselineGrowthAllowance=20

# current counts: "module linter count"
cur="$(awk '
/^== / { mod = $2; next }
/^\* / { gsub(/^\* /, ""); gsub(/^[ ]+/, ""); print mod, $1, $2 }
' "$input")"

rc=0
regressions="$(printf '%s\n' "$cur" | awk -v base="$baseline_file" -v allow="$baselineGrowthAllowance" '
BEGIN {
	while ((getline line < base) > 0) {
		split(line, f, "\t")
		b[f[1] SUBSEP f[2]] = f[3] + 0
	}
}
{
	row = $1 SUBSEP $2
	n = $3 + 0
	if (!(row in b)) {
		printf "NEW: %s %s = %d (no baseline row)\n", $1, $2, n
		next
	}
	if (b[row] == 0 && n > 0) {
		printf "NEW: %s %s = %d (baseline 0)\n", $1, $2, n
		next
	}
	limit = b[row] + int(b[row] * allow / 100)
	if (n > limit) {
		printf "GREW: %s %s = %d (baseline %d, allowance %d%%)\n", $1, $2, n, b[row], allow
	}
}')"

if [ -n "$regressions" ]; then
	echo "$regressions"
	echo "check-lint-baseline: FAIL — advisory lint grew beyond the documented baseline"
	echo "  (regenerate deliberately: scripts/lint-baseline.sh; never bulk-fix the sea)"
	rc=1
else
	cur_total="$(printf '%s\n' "$cur" | awk '{s+=$3} END{print s+0}')"
	base_total="$(awk -F'\t' '{s+=$3} END{print s+0}' "$baseline_file")"
	echo "check-lint-baseline: ok — $cur_total findings vs baseline $base_total"
fi

exit "$rc"
